# Multi-Task Learning Experiment: ModernGBERT Train

# Experiment Identity
experiment_type: "mtl"
model_family: "moderngbert"
model_checkpoint: "LSX-UniWue/ModernGBERT_134M"

# MTL-specific settings
mtl:
  tasks:
    - task_id: "c2a"
      task_name: "call2action"
      num_labels: 2
      task_weight: 1.0
    - task_id: "dbo" 
      task_name: "attacks_on_dbo"
      num_labels: 4
      task_weight: 1.2
    - task_id: "vio"
      task_name: "violence"
      num_labels: 2
      task_weight: 1.0

# Dataset paths for all tasks (train mode)
dataset_paths:
  c2a: "c2a/c2a_hf_dataset"
  dbo: "dbo/dbo_hf_dataset" 
  vio: "vio/vio_hf_dataset"

# Dataset details for all tasks
dataset_details:
  hf_dataset_path_suffix: "mtl/mtl_hf_dataset_train"
  hf_dataset_tokenized_path_suffix: "mtl/mtl_hf_dataset_tokenized_train"
  text_column_name: "description"

# Tokenization Settings
tokenization:
  text_column_name: "description" # The column name in the dataset that contains the text
  padding: "max_length" # Pads the text to processor.model_max_length (1024 for ModernGBERT)
  truncation: true # Truncates the text to processor.model_max_length (1024 for ModernGBERT)
  special_tokens: ["[@URL]", "[@EMAIL]", "[@PRE]", "[@POL]", "[@GRP]", "[@IND]"] # Special tokens (Anonymization tokens. Refer to the data/raw/c2a/readme.md for more information as well as the preprocessing notebook)

# W&B Configuration
wandb_run_name_parts:
  model_arch: "moderngbert"

wandb_tags_add:
  - "moderngbert"
  - "mtl"
  - "train_run"

wandb_notes: "Multi-task learning training run for ModernGBERT on all three subtasks (training data)."

# Model Configuration (for the base model)
model_config:
  trust_remote_code: true

# Training Arguments Override (Default values, pre-sweep)
training_arguments:
  learning_rate: 2.0e-5
  warmup_steps: 500
  per_device_train_batch_size: 4 # Smaller batch sizes for MTL as default than with the other approaches since MTL seems to be more computationally expensive
  per_device_eval_batch_size: 8
  num_train_epochs: 50

# Evaluation Configuration
evaluation:
  metrics_to_load: ["f1", "accuracy", "precision", "recall"] # Metrics used for evaluation
  f1_average_type: "macro" # The average type for the F1 score
  precision_average_type: "macro" # The average type for the precision score
  recall_average_type: "macro" # The average type for the recall score

# MTL Identity
subtask_id: "mtl"
subtask_name: "multi_task_learning"
primary_metric: "f1-macro" # The primary metric for the MTL run